### ISSUE TITLE
Change from ConfigParser to MailSlurp_Client

### ISSUE THREAD

**Issue by marl0nx** [WieszakWare/Hackord#1]
https://github.com/WieszakWare/Hackord/blob/7c786572af1e4769a2e40278176783c4fc4cad93/main.py#L17

**Comment by WieszakWare** [comment]
[beb9b45a61e0b6df50eae32f7f894f5095cd9ab2](https://github.com/WieszakWare/Hackord/commit/beb9b45a61e0b6df50eae32f7f894f5095cd9ab2)
